# Site settings
title: "Austin Propositions"
description: "A simple site about Austin city propositions on the ballot."
baseurl: ''
url: 'https://austinprops.city'
# google_analytics: 'UA-XXXXXX-X'
# twitter_username: 'twitter_username'

# Build settings
markdown: kramdown

exclude:
  - assets
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/bundle

permalink: "/:year/:title/"

plugins:
 - jekyll-archives
 - jekyll-paginate

jekyll-archives:
  enabled: [year]

paginate: 15
